host: 0.0.0.0
port: 8000
served-model-name: Qwen3.8-27B-FP8

model: orcarouter/Qwen3.8-27B-Uncensored-FP8
tensor-parallel-size: 2

# https://huggingface.co/orcarouter/Qwen3.8-27B-Uncensored-FP8#self-host-with-vllm-openai-compatible
language-model-only: true
max-num-seqs: 2
kv-cache-dtype: fp8
enable-auto-tool-choice: true
tool-call-parser: qwen3_coder
reasoning-parser: qwen3
speculative-config: '{"method":"mtp","num_speculative_tokens":3}'
