---
- name: Ensure Samba is installed
  become: true
  ansible.builtin.apt:
    name: samba
    update_cache: true

- name: Ensure the subdirectory is configured in /etc/samba
  become: true
  community.general.ini_file:
    path: /etc/samba/smb.conf
    mode: "0644"
    section: sambashare
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: path
      value: "{{ samba_dir }}"
    - key: read only
      value: "no"
    - key: browsable
      value: "yes"
    - key: vfs objects
      value: catia fruit streams_xattr
  notify: smbd restart

- name: Ensure the firewall allows samba
  become: true
  community.general.ufw:
    rule: allow
    name: Samba
