---
- name: Ensure docker-compose is copied
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/immich-app/immich/releases/download/{{ immich_version }}/docker-compose.yml"
    dest: /opt/immich/docker-compose.yml
    mode: "0644"
  notify: Restart Docker Compose

- name: Ensure .env is updated
  become: true
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/immich/.env
    mode: "0644"
  notify: Restart Docker Compose

- name: Ensure docker compose is up
  become: true
  community.docker.docker_compose_v2:
    project_src: /opt/immich
