---
immich_upload_location: /mnt/immich

elasticsearch_password: "{{ vault_elasticsearch_password }}"

samba_dir: /tank/share
samba_user: neet
samba_password: "{{ vault_samba_password }}"

msmtp_host: smtp.gmail.com
msmtp_from: n33t5hin@gmail.com
msmtp_user: n33t5hin@gmail.com
msmtp_password: "{{ vault_msmtp_password }}"

zed_email: n33t5hin@gmail.com
zed_verbosity: "1"

hf_token: "{{ vault_hf_token }}"

librechat_session_secret: "{{ vault_librechat_session_secret }}"
