---
- name: Ensure Linux Kernel headers are installed
  become: true
  ansible.builtin.apt:
    name: linux-headers-7.0.0-27-generic

- name: Ensure NVIDIA APT keyring is installed
  become: true
  ansible.builtin.apt:
    deb: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2604/x86_64/cuda-keyring_1.1-1_all.deb

- name: Ensure nvidia driver is installed
  become: true
  ansible.builtin.apt:
    pkg:
      - nvidia-driver-pinning-595.71.05
      - libnvidia-compute
      - nvidia-dkms-open
      # Docker から GPU を使うのに必要
      - nvidia-container-toolkit
      - nvidia-container-toolkit-base
      - libnvidia-container-tools
      - libnvidia-container1

- name: Set power limit to GPUs
  become: true
  ansible.builtin.template:
    src: nvidia-power-limit.service.j2
    dest: /etc/systemd/system/nvidia-power-limit.service
    mode: "0644"
  notify: Restart nvidia-power-limit

- name: Ensure nvidia-power-limit is enabled
  become: true
  ansible.builtin.service:
    name: nvidia-power-limit
    enabled: true
    state: started
