---
- name: Ensure avahi is installed
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: avahi-daemon

- name: Ensure avahi is enabled
  become: true
  ansible.builtin.service:
    name: avahi-daemon
    enabled: true
    state: started
