---
- name: Ensure hf is installed
  become: true
  ansible.builtin.apt:
    name: python3-huggingface-hub

- name: Ensure club-3090 is cloned
  become: true
  ansible.builtin.git:
    repo: https://github.com/noonghunna/club-3090.git
    dest: /opt/club-3090
    version: v0.10.1
    depth: 1
  notify: Restart vLLM Docker Compose

- name: Ensure .env is updated
  become: true
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/club-3090/.env
    mode: "0644"
  notify: Restart vLLM Docker Compose

- name: Ensure model is cached
  become: true
  ansible.builtin.command:
    chdir: /opt/club-3090
    argv:
      - scripts/setup.sh
      - qwen3.6-27b
    creates: /opt/club-3090/models-cache/qwen3.6-27b-autoround-int4/model-*.safetensors
  environment:
    HF_TOKEN: "{{ hf_token }}"
    MODEL_DIR: models-cache
  notify: Restart vLLM Docker Compose

- name: Ensure docker compose is up
  become: true
  community.docker.docker_compose_v2:
    project_src: /opt/club-3090/models/qwen3.6-27b/vllm/compose/dual/autoround-int4
    env_files:
      - /opt/club-3090/.env
    files:
      - fp8-mtp.yml
