---
- name: Ensure mail comand is available
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: bsd-mailx

- name: Ensure zedrc is set
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zfs/zed.d/zed.rc
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}=\"{{ item.value }}\""
  loop:
    - key: ZED_EMAIL_ADDR
      value: "{{ zed_email }}"
    - key: ZED_NOTIFY_VERBOSE
      value: "{{ zed_verbosity }}"
  notify: restart zed
