# https://www.librechat.ai/docs/configuration/librechat_yaml
version: 1.3.13
cache: true

endpoints:
  custom:
    - name: "vLLM"
      apiKey: "vllm"
      baseURL: "http://host.docker.internal:8000/v1"
      models:
        default: ["Qwen3.6-27B-FP8"]
        fetch: true
      titleConvo: true
      titleModel: "current_model"
      titleMessageRole: "user"
      summarize: false
      summaryModel: "current_model"

webSearch:
  searchProvider: "tavily"
  scraperProvider: "tavily"
  rerankerType: "none"

