---
- name: Prepare shared settings
  hosts: all
  roles:
    - avahi

- name: Update store-mitaka-01
  hosts: store-mitaka-01.local
  roles:
    - samba
    - msmtp
    - zed
    - nfs_server

- name: Update compute-mitaka-01
  hosts: compute-mitaka-01.local
  roles:
    - geerlingguy.docker
    - nfs_client
    - immich
    - elasticsearch
    - cloudflared
  # https://github.com/geerlingguy/ansible-role-docker/issues/490
  become: true

- name: Update compute-mitaka-02
  hosts: compute-mitaka-02.local
  roles:
    - nfs_client
    - nvidia
    - geerlingguy.docker
    - vllm
    - librechat
    - caddy
  become: true
