- name: Data Store
  hosts: store
  roles:
    - avahi
    - samba
    - msmtp
    - zed
    - nfs_server

- name: Hosting Immich + Elasticsearch + Gateway
  hosts: compute
  roles:
    - avahi
    - geerlingguy.docker
    - nfs_client
    - immich
    - elasticsearch
    - cloudflared
  # https://github.com/geerlingguy/ansible-role-docker/issues/490
  become: true
