name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UV_FROZEN: "true"
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Create .vault_pass
        run: echo "$ANSIBLE_VAULT_PASS" > .vault_pass
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}

      - name: Ansible Lint
        run: uv run ansible-lint
