# roles/cloudflared/tasks/main.yml
- name: Ensure GPG key is downloaded
  ansible.builtin.get_url:
    url: https://pkg.cloudflare.com/cloudflare-public-v2.gpg
    dest: /usr/share/keyrings/cloudflare-public-v2.gpg
    mode: '0644'

- name: Ensure apt respoitory is added
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloudflare-public-v2.gpg] https://pkg.cloudflare.com/cloudflared any main"
    filename: cloudflared

- name: Ensure cloudflared is installed
  ansible.builtin.apt:
    name: cloudflared
    update_cache: yes

- name: Install cloudflared service
  ansible.builtin.command:
    cmd: cloudflared service install {{ vault_cloudflared_token }}
    # これでいいのかよくわかっていない
    creates: /etc/systemd/system/cloudflared.service
